### ISSUE TITLE
Learner Sign Up - Date of Birth Dropdown

### ISSUE THREAD

**Issue by vcroptech** [crocsocial/vLearnLive2.0#1]
a.santy and Mange password is overlapping the DOB dropdown. Pls refer attached screenshot.

![image](https://user-images.githubusercontent.com/19173148/54377613-7b177e80-46ab-11e9-89fb-4ab7a4a24538.png)

**Comment by satishverma143** [comment]
I have resolved this issue and if still you faced then please clear your browser cache & cookies.

**Comment by vcroptech** [comment]
ok
